// packages/ngx-bootstrap-docs/src/components/sample-box/sample-box.tsx
import { component$, Slot } from '@builder.io/qwik';
import {Tab, Tabset} from "ngx-bootstrap";

export default component$((props:{html?: string, ts?: string, style?: string, spec?: string}) => {
    return (
        <>
            <div class="section bd-example">
                <Slot/>
            </div>
            <div class="section">
                <div class="item">
                {!!(props.html || props.ts || props.spec || props.style) && (
                    <Tabset>
                        {!!props.html && (
                            <Tab heading="template" id={'tab-template'} active={true}
                            customClass={'code-tab cursor-pointer'}>
                                <pre className="prettyprint linenums lang-html">{props.html}</pre>
                            </Tab>
                        )}

                        {!!props.ts && (
                            <Tab heading="component" id={'tab-component'}
                            customClass={'code-tab cursor-pointer'}>
                                <pre className="prettyprint linenums lang-js">{props.ts}</pre>
                            </Tab>
                        )}

                        {!!props.spec && (
                            <Tab heading="tests" id={'tab-tests'}
                            customClass={'code-tab cursor-pointer'}>
                                <pre className="prettyprint linenums lang-js">{props.spec}</pre>
                            </Tab>
                        )}

                        {!!props.style && (
                            <Tab heading="tests" id={'tab-style'}
                            customClass={'code-tab cursor-pointer'}>
                                <pre className="prettyprint linenums lang-css">{props.style}</pre>
                            </Tab>
                        )}
                    </Tabset>
                )}
            </div>
            </div>
        </>
    );
});

// libs/common-docs/src/lib/api-docs/sample-box/sample-box.component.ts
import { Component, Input } from '@angular/core';

@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: 'ng-sample-box',
  templateUrl: './sample-box.component.html',
  
})
export class SampleBoxComponent {
  @Input() ts?: string;
  @Input() html?: string;
  @Input() spec?: string;
  @Input() style?: string;
}

<div class="section bd-example"><ng-content></ng-content></div>
<div class="section">
  <div class="item">
    @if (html || ts || spec || style) {
      <tabset>
        @if (html) {
          <tab heading="template" [customClass]="'code-tab'">
            <pre class="prettyprint linenums lang-html">{{html}}</pre>
          </tab>
        }
        @if (ts) {
          <tab heading="component" [customClass]="'code-tab'">
            <pre class="prettyprint linenums lang-js">{{ts}}</pre>
          </tab>
        }
        @if (spec) {
          <tab heading="tests" [customClass]="'code-tab'">
            <pre class="prettyprint linenums lang-js">{{spec}}</pre>
          </tab>
        }
        @if (style) {
          <tab heading="style" [customClass]="'code-tab'">
            <pre class="prettyprint linenums lang-css">{{style}}</pre>
          </tab>
        }
      </tabset>
    }
  </div>
</div>
