// packages/ngx-bootstrap-docs/src/components/examples-component/examples-component.tsx
import {component$, useClientEffect$, $, Slot, useStore} from '@builder.io/qwik';
import {getQueryParams} from "~/routing/routing";
import {tabsNames} from "~/components/docs-section/docs-section";
import SampleBox from '~/components/sample-box/sample-box';
import { ContentSection } from '~/models/content-section.model';


export default component$((props: {section:ContentSection}) => {
    const state = useStore({
        tabName: tabsNames.overview
    })

    useClientEffect$(() => {
        const key = tabsNames[getQueryParams('tab') as keyof typeof tabsNames]
        state.tabName = key || tabsNames.overview;
        console.log(props.section)
    });

    // const openStackBlitzDemo = $((comp, html) => {
    //     console.log(comp, html);
    // })

    return (

        <div class='examples'>
        {!!props.section?.description && (<p dangerouslySetInnerHTML={props.section?.description}></p>)}

        {props.section?.content?.map((item) => (
            <div class="example-section">
                {!!item.title &&
                    (<h3 id={item.anchor} class="d-flex justify-content-between">
                        { item.title }

                        {// @ts-ignore
                            !!(item?.component || state.tabName === 'examples') && (
                            <p class="m-0">
                                {!!(item.title !== 'Accessibility' && state.tabName !== 'examples') &&
                                    (<a
                                    title="Open this demo in StackBlitz"
                                    href="#"
                                    class="stackblitz-link"
                                    // onclick$={() => {
                                    //     // @ts-ignore
                                    //     openStackBlitzDemo(item?.component?.default, item?.html?.default)
                                    // }}
                                    >
                                    <img src="/images/stackblitz.png" alt="" width="20"/>
                                    </a>
                                    )
                                }

                                {/*<a *ngIf="tabName !== 'examples'" class="anchor-link d-inline-block" routerLink="." [fragment]="item.anchor">#</a>*/}
                                {/*<a *ngIf="item.title !== 'Accessibility' && tabName === 'examples'" [queryParams]="{tab: 'overview'}" routerLink="." [fragment]="initFragment(item.anchor)">*/}
                                {/*<img src="assets/images/icons/icon-code.svg" alt="" width="20">*/}
                                {/*</a>*/}
                            </p>
                        )}

                    </h3>)
                }

                {    // @ts-ignore
                    !!item.description && (
                    <p
                        // @ts-ignore
                        dangerouslySetInnerHTML={item.description}></p>
                )}

            <SampleBox
                // @ts-ignore
                html={item.html?.default} ts={item.component?.default} style={item.style}>
                <Slot></Slot>
            {/*<ng-container *ngComponentOutlet="item.outlet"></ng-container>*/}
            </SampleBox>
            </div>


        ))}


        </div>

    );
});

// libs/common-docs/src/lib/demo-section-components/demo-examples-section/examples.component.ts
import { Component, HostListener } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import sdk from '@stackblitz/sdk';

import { ContentSection } from '../../models/content-section.model';
import { ComponentExample } from '../../models/components-examples.model';
import { main } from './stackblitz/main';
import { polyfills } from './stackblitz/polyfills';
import { getAppModuleCode, NgxModuleData } from './stackblitz/app.module';
import { getIndexHtmlCode } from './stackblitz/html';
import { getComponentClassName, getTagName, getTemplateFileName, getCSSCodeDatepickerCustomClass } from './stackblitz/helpers';

@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: 'examples',
  templateUrl: './examples.component.html'
})
export class ExamplesComponent {
  examples: ComponentExample[];
  moduleData: NgxModuleData;

  constructor(public section: ContentSection, private route: ActivatedRoute, router: Router) {
    this.examples = section.content as ComponentExample[];
    this.moduleData = this.route.snapshot.data && this.route.snapshot.data[1];
    this.moduleData.moduleRoute = router.routerState.snapshot.url;
  }

  @HostListener('document:click', ['$event'])
  preventEmptyHrefNav(event: MouseEvent & { target: Element }): void {
    let element: Element = event.target;
    let preventNav = element.getAttribute('href') === '#';

    if (preventNav) {
      event.preventDefault();

      return;
    }

    if (element.tagName !== 'A') {
      while (element.parentElement && element !== document.body) {
        if (preventNav) {
          event.preventDefault();

          return;
        }
        element = element.parentElement;
        preventNav = element.getAttribute('href') === '#';
      }
    }
  }

  openStackBlitzDemo(ts?: string, html?: string) {
    if (!ts || !html) {
      return;
    }

    const className = getComponentClassName(ts);
    const tag = getTagName(ts);
    const templateName = getTemplateFileName(ts);
    if (tag && className) {
      const project = {
        files: <any>{
          'index.html': getIndexHtmlCode(tag, this.moduleData),
          'styles.css': `body {padding: 30px; position: relative}
        ${this.moduleData.moduleRoute === '/sortable' ?
            `.sortable-item {
      padding: 6px 12px;
      margin-bottom: 4px;
      font-size: 14px;
      line-height: 1.4em;
      text-align: center;
      cursor: grab;
      border: 1px solid transparent;
      border-radius: 4px;
      border-color: #adadad;
    }

    .sortable-item-active {
      background-color: #e6e6e6;
      box-shadow: inset 0 3px 5px rgba(0,0,0,.125);
    }

    .sortable-wrapper {
      min-height: 150px;
    }` : ''}
    ${this.moduleData.moduleRoute === '/accordion' ?
            `.card.customClass,
.card.customClass .card-header,
.panel.customClass {
  background-color: #5bc0de;
  color: #fff;
}
.panel.customClass .panel-body {
  background-color: #337aa7;
}` : ''}`,
          '.angular-cli.json': `{"apps": [{"styles": ["styles.css"]}]}`,
          'main.ts': main,
          'polyfills.ts': polyfills,
          'app/app.module.ts': getAppModuleCode(className, this.moduleData),
          'app/ngx-bootstrap-demo.component.ts': this.getTs(ts)
        },
        dependencies: {
          '@angular/animations': 'latest',
          'web-animations-js': 'latest',
          'ngx-bootstrap': 'next'
        },
        title: 'stackblitz demo',
        description: 'stackblitz demo',
        template: 'angular-cli'
      };
      if (className === 'DemoDatepickerDateCustomClassesComponent') {
        project.files['app/date-custom-classes.scss'] = getCSSCodeDatepickerCustomClass();
      }
      project.files[`app/${templateName}`] = this.getHtml(html);

      sdk.openProject(project);
    }
  }

  private getHtml(html: string): string {
    return this.moduleData.moduleRoute === '/carousel' ?
      html.replace(/src="/g, 'src="https://valor-software.com/ngx-bootstrap/') : html;
  }

  private getTs(ts: string): string {
    return this.moduleData.moduleRoute === '/carousel' ?
      ts.replace(/assets/g, 'https://valor-software.com/ngx-bootstrap/assets') : ts;
  }
}


@if (section) {
  @if (section.description) {
    <p [innerHTML]="section.description"></p>
  }
  @for (item of examples; track item) {
    <div class="example-section">
      @if (item.title) {
        <h3 [attr.id]="item.anchor" class="d-flex justify-content-between">
          {{ item.title }}
          @if (item?.component || tabName === 'examples') {
            <p class="m-0">
              @if (item.title !== 'Accessibility' && tabName !== 'examples') {
                <a
                  title="Open this demo in StackBlitz"
                  href="#"
                  class="stackblitz-link"
                  (click)="openStackBlitzDemo($safeNavigationMigration(item?.component?.default), $safeNavigationMigration(item?.html?.default))">
                  <img src="assets/images/stackblitz.png" alt="" width="20">
                </a>
              }
              @if (tabName !== 'examples') {
                <a class="anchor-link d-inline-block" routerLink="." [fragment]="item.anchor">#</a>
              }
              @if (item.title !== 'Accessibility' && tabName === 'examples') {
                <a [queryParams]="{tab: 'overview'}" routerLink="." [fragment]="initFragment(item.anchor)">
                  <img src="assets/images/icons/icon-code.svg" alt="" width="20">
                </a>
              }
            </p>
          }
        </h3>
      }
      @if (item.description) {
        <p [innerHTML]="item.description"></p>
      }
      <ng-sample-box [ts]="$safeNavigationMigration(item?.component?.default)" [html]="$safeNavigationMigration(item?.html?.default)" [style]="item.style ">
        <ng-container *ngComponentOutlet="item.outlet"></ng-container>
      </ng-sample-box>
    </div>
  }
}
