// libs/common-docs/src/lib/demo-section/demo-section.component.ts
import { Component, Input } from '@angular/core';

@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: 'demo-section',
  templateUrl: './demo-section.component.html'
})
export class DemoSectionComponent {
  @Input() name: string | undefined;
  @Input() src: string | undefined;
  @Input() html: string | undefined;
  @Input() ts: string | undefined;

  @Input() componentContent: unknown;
}

<main class="main">
<!--  <sidebar class="sidebar"></sidebar>-->

  <section class="main-container">
    <div class="content">
      <div class="content-header">
        <h1 *ngIf="name || src">{{name}}
          <a [href]="src" target="_blank" rel="noopener">
            <img src="assets/images/link-doc.png" alt="component on github"/>
          </a>
        </h1>
      </div>

      <div id="content" class="content-box">
        <div id="example" class="section">
          <div class="item">
            <ng-content></ng-content>
          </div>
        </div>
      </div>
    </div>
<!--    <app-footer></app-footer>-->
  </section>

<!--  <add-nav *ngIf="componentContent" class="add-nav" [componentContent]="componentContent"></add-nav>-->

</main>

// packages/ngx-bootstrap-docs/src/components/demo-section/demo-section.tsx
import { component$, Slot } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';

export default component$((props: {
  name?: string,
  src?: string,
  html?: string,
  ts?: string
}) => {
  return (
    <main class="main">
      <section class="main-container transition-option">
        {/*<bread-crumbs></bread-crumbs>*/}
        <div class="content-box">
          <div class="content w-100">
            <div class="content-header">


              {(props.name || props.src) &&
  (              <h1>{props.name}
                <Link href={props.src} target="_blank" rel="noopener">
                <img src="/images/link-doc.png" alt="component on github"/>
                </Link>
                </h1>)
              }
        </div>

        <div id="content">
          <div id="example" class="section">
            <div class="item">
              <Slot/>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>
</main>
  );
});
