// libs/common-docs/src/lib/common/sidebar/sidebar.component.ts
import { ActivatedRoute, NavigationEnd, Router, Routes, UrlSegment } from '@angular/router';
import { Component, HostBinding, Inject, inject, Renderer2 } from '@angular/core';

import { AvailableBsVersions, currentBsVersion, getBsVer, IBsVersion, setTheme } from 'ngx-bootstrap/utils';
import { StyleManager } from '../../theme/style-manager';
import { ThemeStorage } from '../../theme/theme-storage';
import { DOCS_TOKENS } from '../../tokens/docs-routes-token';
import { NestedRouteType, SidebarRouteItemValueType, SidebarRoutesType } from '../../models/sidebar-routes.model';
import { SIDEBAR_ROUTES } from '../../tokens/docs-sidebar-routes-token';
import { initNestedRoutes } from './helpers/sidebar-helpers';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';

const _bs4Css = 'assets/css/bootstrap-4.5.3/css/bootstrap.min.css';
const _bs5Css = 'assets/css/bootstrap-5.2.3/css/bootstrap.min.css';

@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: 'sidebar',
  templateUrl: './sidebar.component.html',
  standalone: false
})
export class SidebarComponent {
  isShown = false;

  routesStructure?: SidebarRoutesType;
  objectKeys = Object.keys;
  @HostBinding('class.menuIsOpened') menuIsOpened = true;

  get bsCssFile(): string {
    if (this.currentTheme === 'bs5') {
      return _bs5Css;
    }

    return _bs4Css;
  }

  get _bsVersions(): IBsVersion {
    return getBsVer();
  }
  search = { text: '' };
  currentTheme?: AvailableBsVersions;
  bodyElement: HTMLBodyElement;

  constructor(
    private activatedRoute: ActivatedRoute,
    private router: Router,
    private themeStorage: ThemeStorage,
    public styleManager: StyleManager,
    @Inject(DOCS_TOKENS) _routes: Routes,
    @Inject(SIDEBAR_ROUTES) sidebarRoutesStructure: SidebarRoutesType
  ) {
    if (innerWidth <= 991) {
      this.menuIsOpened = false;
    }
    this.bodyElement = inject(Renderer2).selectRootElement('body', true);
    this.routesStructure = initNestedRoutes(_routes, sidebarRoutesStructure);
    this.initBodyClass();
    this.firstMenuIniting(_routes);
    this.router.events.pipe(takeUntilDestroyed()).subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.firstMenuIniting(_routes);
      }
    });
    const themeFromUrl = this.activatedRoute.snapshot.queryParams['_bsVersion'];
    const currentTheme = themeFromUrl || this.themeStorage.getStoredTheme();
    if (currentTheme) {
      this.installTheme(currentTheme);
    }
  }

  get sideBarItemIsOpened(): void | keyof SidebarRoutesType {
    for (const item in this.routesStructure) {
      if (this.routesStructure[item as keyof SidebarRoutesType].isOpened) {
        return item as keyof SidebarRoutesType;
      }
    }
  }

  firstMenuIniting(routes: Routes) {
    this.resetMenuItems();
    this.openMenuWithRoutePath(this.checkRoutePath(), routes);
  }

  installTheme(theme: AvailableBsVersions) {
    setTheme(theme);
    this.currentTheme = currentBsVersion();
    this.styleManager.setStyle('theme', this.bsCssFile);
    if (this.currentTheme) {
      this.themeStorage.storeTheme(this.currentTheme);
    }
  }

  toggleSideBar(value?: boolean) {
    if (typeof value === 'undefined') {
      this.menuIsOpened = !this.menuIsOpened;
    }

    if (typeof value !== 'undefined' && value !== this.menuIsOpened) {
      this.menuIsOpened = value;
    }

    this.initBodyClass();
  }

  initBodyClass() {
    if (this.menuIsOpened) {
      this.bodyElement.classList.add('menuIsOpened');
    } else {
      this.bodyElement.classList.remove('menuIsOpened');
    }
  }

  toggleMenuItem(event: Event, value: string): void {
    event.stopPropagation();
    if (this.routesStructure) {
      const key = value.toLowerCase();
      this.resetMenuItems();
      this.routesStructure[key as keyof SidebarRoutesType].isOpened =
        !this.routesStructure[key as keyof SidebarRoutesType].isOpened;
      if (this.routesStructure[key as keyof SidebarRoutesType].path) {
        this.router.navigate([this.routesStructure[key as keyof SidebarRoutesType].path]);
      }
    }
  }

  resetMenuItems() {
    for (const item in this.routesStructure) {
      this.routesStructure[item as keyof SidebarRoutesType].isOpened = false;
      this.resetSemiMenu(this.routesStructure[item as keyof SidebarRoutesType].nestedRoutes);
    }
  }

  openSemiItemMenu(semiMenu: NestedRouteType, nestedRoutes: NestedRouteType[]) {
    this.resetSemiMenu(nestedRoutes);
    semiMenu.isOpened = true;
    if (semiMenu.path) {
      this.router.navigate([semiMenu.path]);
      this.closeAdaptiveMenu();
    }
  }

  closeAdaptiveMenu() {
    if (innerWidth <= 991) {
      this.menuIsOpened = false;
      this.toggleSideBar(false);
    }
  }

  resetSemiMenu(nestedRoutes: NestedRouteType[]) {
    nestedRoutes.forEach((item) => {
      item.isOpened = false;
    });
  }

  checkRoutePath(): string[] {
    const tree: UrlSegment[] = this.router.parseUrl(this.router.url).root?.children?.['primary']?.segments;
    const result = new Set<string>();
    tree?.map((segment) => {
      result.add(segment.path);
    });
    return [...result];
  }

  openMenuWithRoutePath(path: string[], routes: Routes) {
    if (!this.routesStructure) {
      return;
    }

    if (path.length > 1) {
      this.openMenuWithRoute(`/${path[0]}/${path[1]}`, path[0]);
      return;
    }

    const currentRoute = routes.filter((route) => route.path === path[0]);
    if (
      !currentRoute?.length ||
      (!currentRoute[0].data?.[1]?.sideBarParentTitle && !currentRoute[0].children?.length)
    ) {
      return;
    }

    const key = currentRoute[0].children?.length ? currentRoute[0].path : currentRoute[0].data?.[1]?.sideBarParentTitle;
    this.openMenuWithRoute(path[0], key);
  }

  openMenuWithRoute(routePath: string, parentPath: string) {
    if (!this.routesStructure) {
      return;
    }

    this.routesStructure[parentPath as keyof SidebarRoutesType].isOpened = true;
    const currentMenuItem = this.routesStructure?.[parentPath as keyof SidebarRoutesType].nestedRoutes.find(
      (route) => route.path === routePath
    );
    this.setMenuProperties(currentMenuItem);
  }

  setMenuProperties(currentMenuItem?: NestedRouteType) {
    if (!currentMenuItem) {
      return;
    }

    const params = this.router.parseUrl(this.router.url).queryParams;
    currentMenuItem.isOpened = true;
    currentMenuItem.fragments.forEach((item: { title: string; path: string; isOpened: boolean }) => {
      item.isOpened = item.path === params['tab'];
    });
  }

  getRouteStructureKey(value: string): SidebarRouteItemValueType | undefined {
    return this.routesStructure?.[value as keyof SidebarRoutesType];
  }
}

<ng-container *ngIf="routesStructure">
  <div class="sidebar-search icon w-100">
    <button id="mobile-main-menu" type="button" (click)="toggleSideBar()" class="align-self-baseline">
      <img src="assets/images/icons/menu-left.svg" alt="left menu">
    </button>
    <search-input [showInput]="false" class="w-100"></search-input>
  </div>
  <div class="mobile-menu" [class.menuIsOpened]="menuIsOpened" *ngIf="routesStructure && routesStructure['documentation']?.nestedRoutes?.length">
    <div class="bootstrap-version transition-option">
      <span class="transition-option" [class.hideText]="!menuIsOpened">Bootstrap: </span>
      <div class="flex-nowrap d-flex">
        <button class="btn" type="button" [class.selected]="_bsVersions.isBs3" (click)="installTheme('bs3')">3</button>
        <button class="btn" type="button" [class.selected]="_bsVersions.isBs4" (click)="installTheme('bs4')">4</button>
        <button class="btn" type="button" [class.selected]="_bsVersions.isBs5"  (click)="installTheme('bs5')">5</button>
      </div>
    </div>
    <div class="sidebar-content position-relative w-100">
      <ul class="sidebar-list">
        <li *ngFor="let route of objectKeys(routesStructure)"
            [class.active]="getRouteStructureKey(route)?.isOpened"
            [class.icon]="getRouteStructureKey(route)?.nestedRoutes?.length && menuIsOpened"
            (click)="toggleSideBar(true); toggoleMenuItem($event, route)"
            class="sidebar-item-main "
        >
          <div class="sidebar-list-box">
            <img [src]="getRouteStructureKey(route)?.icon" alt="sidebar icon">
            <span [class.hideText]="!menuIsOpened" [class.m-0]="!menuIsOpened" class="transition-option" *ngIf="!getRouteStructureKey(route)?.path; else elseBlock">
              {{getRouteStructureKey(route)?.title}}
            </span>
            <ng-template #elseBlock>
              <a [class.hideText]="!menuIsOpened" [class.m-0]="!menuIsOpened" class="transition-option">
                {{getRouteStructureKey(route)?.title}}
              </a>
            </ng-template>
          </div>
        </li>
      </ul>
      <ul *ngIf="menuIsOpened && sideBarItemIsOpened" class="sidebar-list scroll-list">
        <li *ngFor="let route of routesStructure[sideBarItemIsOpened].nestedRoutes"
            [routerLinkActive]="['active']"
            [routerLinkActiveOptions]="{exact: true}"
            class="w-100"
        >
          <div class="sidebar-list-box d-flex flex-column secondary-items" [class.show]="route.isOpened">
            <p (click)="openSemiItemMenu(route, routesStructure[sideBarItemIsOpened].nestedRoutes)">{{route.title}}</p>
            <div class="sidebar-list sidebar-list-fragment" [class.show]="route.isOpened" *ngIf="route.fragments.length">
              <div class="sidebar-item sidebar-item-fragment" *ngFor="let item of route.fragments">
                <a [routerLink]="[getRouteLink(route.path, routesStructure[sideBarItemIsOpened].path)]" [queryParams]="{tab: item.path}">{{item.title}}</a>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
  <div class="double-arrow position-absolute" (click)="toggleSideBar()" [class.menu-opened]="menuIsOpened"></div>
</ng-container>

// packages/ngx-bootstrap-docs/src/components/sidebar/sidebar.tsx
import {component$, $, useOn, useOnWindow, useClientEffect$, useStore, useTask$} from '@builder.io/qwik';
import * as React from 'react';
import SearchInput from "~/components/header/serach-input";
import {
  SidebarRoutesType,
  SidebarRouteItemValueType,
  NestedRouteType,
  refactorPathName, refactorPathsNames, toggleMenuItem, resetSemiMenu, initBodyClass, firstMenuIniting, setLocationPath
} from "~/routing/routing";
import { useLocation, useNavigate } from "@builder.io/qwik-city";
import { CustomLink } from "~/routing/link";
import {AvailableBsVersions, ThemeStorage} from "~/components/sidebar/theme-storage";
import { setTheme, currentBsVersion } from './theme-provider';
import {StyleManager} from "~/components/sidebar/styleManager";



const _bs4Css = '/css/bootstrap-4.5.3/css/bootstrap.min.css';
const _bs5Css = '/css/bootstrap-5.2.3/css/bootstrap.min.css';

interface IState {
  menuIsOpened: boolean;
  routesStructure: Partial<SidebarRoutesType>,
  currentTheme: AvailableBsVersions | null;
}

const themeStorage = new ThemeStorage();
const styleManager = new StyleManager();

export default component$(() => {
  const navigation = useNavigate();
  const location = useLocation();

  const state = useStore<IState>({
    menuIsOpened: true,
    routesStructure: {},
    currentTheme: themeStorage.getStoredTheme()
  }, {recursive: true});

  useTask$(({track}) => {
    const theme = track(() => state.currentTheme);
    if (state.currentTheme) {
      installTheme(state.currentTheme);
    }
  })

  useClientEffect$(() => {
    if (!Object.keys(state.routesStructure).length) {
      setLocationPath({path: location.pathname, query: location.query});
      state.routesStructure = firstMenuIniting(location.pathname);
    }

    initBodyClass(state.menuIsOpened);

    const listener = ()=> {
      setTimeout(() => {
        setLocationPath({path: location.pathname, query: location.query});
        firstMenuIniting(location.pathname);
      },100)
    }

    window.addEventListener('locationchange', listener);
    return ()=> {window.removeEventListener('locationchange',listener)}
  });

  function getSideBarItemIsOpened (): string | keyof SidebarRoutesType {
    for (const item in state.routesStructure) {
      if (state.routesStructure[item as keyof SidebarRoutesType]?.isOpened) {
        return item as keyof SidebarRoutesType;
      }
    }

    return '';
  }

  function getBsCssFile(currentTheme?: AvailableBsVersions): string {
    if (currentTheme === 'bs5') {
      return _bs5Css;
    }

    return _bs4Css;
  }

  const clickedMenuItem = $((value?: string) => {
    if (!value) {
      return;
    }

      navigation.path = `${value}`;
      window.dispatchEvent(new Event('locationchange'));
  });

  const closeAdaptiveMenu = $(() => {
    if (innerWidth <= 991) {
      state.menuIsOpened = false;
    }
  });

  const installTheme = $((theme: AvailableBsVersions) => {
    setTheme(theme);
    const currentTheme = currentBsVersion();
    styleManager.setStyle('theme', getBsCssFile(currentTheme));
    if (currentTheme) {
      themeStorage.storeTheme(currentTheme);
    }
  })

  return (
    <div id="sidebar" className={`sidebar ${state.menuIsOpened ? 'menuIsOpened' : ''}`}>
      <div className="sidebar-search icon w-100">
        <button id="mobile-main-menu" type="button" className="align-self-baseline" onClick$={() => {state.menuIsOpened = !state.menuIsOpened}}>
          <img src="/images/icons/menu-left.svg" alt="left menu"/>
        </button>
        <div class="w-100">
          <SearchInput showInput={false}></SearchInput>
        </div>
      </div>

      <div className={`mobile-menu w-100 ${state.menuIsOpened ? 'menuIsOpened' : ''}`}>
        <div class="bootstrap-version transition-option">
          <span className={`transition-option ${!state.menuIsOpened ? 'hideText' : ''}`}>Bootstrap: </span>
          <div class="flex-nowrap d-flex">
            {/*<button type="button" className={`btn ${state.currentTheme === 'bs4' ? 'selected' : ''}`} onClick$={(() => {installTheme('bs4')})}>4</button>*/}
            {/*<button type="button" className={`btn ${state.currentTheme === 'bs5' ? 'selected' : ''}`} onClick$={(() => {installTheme('bs5')})}>5</button>*/}
          </div>
        </div>
      </div>

      <div class="sidebar-content position-relative w-100">
        <ul className={'sidebar-list'}>
          {Object.keys(state.routesStructure).map( (item) =>{
              if (state.routesStructure[item as keyof SidebarRoutesType]?.title) {
                return <li
                  key={item}
                  onClick$={() => {
                    clickedMenuItem(state.routesStructure[item as keyof SidebarRoutesType]?.path);
                  }}
                  className={`
                 sidebar-item-main ${state.routesStructure[item as keyof SidebarRoutesType]?.isOpened ? 'active' : ''}
                 ${state.routesStructure[item as keyof SidebarRoutesType]?.nestedRoutes?.length && state.menuIsOpened ? 'icon' : ''}
                 `}
                >
                  <div className="sidebar-list-box">

                    <img src={
                      state.routesStructure[item as keyof SidebarRoutesType]?.icon
                    } alt="sidebar icon"/>
                    {state.routesStructure[item as keyof SidebarRoutesType]?.path && (
                      <span className={`transition-option ${!state.menuIsOpened ? 'hideText m-0' : ''}`}>
                      {state.routesStructure[item as keyof SidebarRoutesType]?.title}
                     </span>
                    )}
                    {!state.routesStructure[item as keyof SidebarRoutesType]?.path && (
                      <a className={`transition-option ${!state.menuIsOpened ? 'hideText m-0' : ''}`} href="javascript:void(0);">
                        {state.routesStructure[item as keyof SidebarRoutesType]?.title}
                      </a>
                    )}
                  </div>
                </li>
              }
            }
          )}
        </ul>
        {(state.menuIsOpened && !!getSideBarItemIsOpened()) && (
          <ul className="sidebar-list scroll-list">
            {
              // @ts-ignore
              state.routesStructure[getSideBarItemIsOpened() as keyof typeof SidebarRoutesType]?.nestedRoutes?.map(item => {
                return (
                  <li className={`w-100 ${item.isOpened ? 'active' : ''}`}>
                    <div className={
                      `sidebar-list-box d-flex flex-column secondary-items
                        ${// @ts-ignore
                        item.isOpened ? 'show' : ''}`
                    }>
                      <p onClick$={() => {
                        clickedMenuItem(item.path);
                        closeAdaptiveMenu();
                      }
                      }>{item.title}</p>
                      {!!item.fragments?.length && (
                        <div className={`sidebar-list sidebar-list-fragment ${item.isOpened ? 'show' : ''}`}>
                          {item.fragments.map((fragment: {title: string, path: string, isOpened: boolean}) => {
                            return (<div className={`sidebar-item sidebar-item-fragment ${fragment.isOpened ? 'active' : ''}`}>
                              <CustomLink path={`${item.path}?tab=${fragment.path}`}>{fragment.title}</CustomLink>
                            </div>)
                          })}
                        </div>
                      )}
                    </div>
                  </li>
                )
              })
            }
          </ul>
        )}
      </div>
      <div className={`double-arrow position-absolute ${state.menuIsOpened ? 'menu-opened' : ''}`} onClick$={() => state.menuIsOpened = !state.menuIsOpened}></div>
    </div>
)
})
