// packages/ngx-bootstrap-docs/src/components/demo-section/demo-section.tsx
import { component$, Slot } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';

export default component$((props: {
  name?: string,
  src?: string,
  html?: string,
  ts?: string
}) => {
  return (
    <main class="main">
      <section class="main-container transition-option">
        {/*<bread-crumbs></bread-crumbs>*/}
        <div class="content-box">
          <div class="content w-100">
            <div class="content-header">


              {(props.name || props.src) &&
  (              <h1>{props.name}
                <Link href={props.src} target="_blank" rel="noopener">
                <img src="/images/link-doc.png" alt="component on github"/>
                </Link>
                </h1>)
              }
        </div>

        <div id="content">
          <div id="example" class="section">
            <div class="item">
              <Slot/>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>
</main>
  );
});

// demo/src/app/shared/demo-section/demo-section.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'demo-section',
  templateUrl: './demo-section.component.html'
})
export class DemoSectionComponent {
  @Input() public name:string;
  @Input() public titleDoc:string;
  @Input() public src:string;
  @Input() public html:string;
  @Input() public ts:string;
  @Input() public doc:string;
}

<main class="main">
  <sidebar class="sidebar"></sidebar>

  <section class="main-container">
    <div class="content">
      <div class="content-header">
        <h1 *ngIf="name || src">{{name}}
          <a [href]="src" target="_blank" rel="noopener">
            <img src="assets/images/link-doc.png" alt="link to doc"/>
          </a>
        </h1>
      </div>

      <div id="content" class="content-box">
        <!-- remove this -->
        <p class="description" [innerHTML]="titleDoc" *ngIf="titleDoc"></p>

        <div id="example" class="section">
          <div class="item">
            <ng-content></ng-content>
          </div>
        </div>

        <!-- remove this -->
        <div id="markup" class="section" *ngIf="html || ts">
          <h3>Markup</h3>

          <div class="item">
            <tabset>
              <tab heading="Markup" *ngIf="html">
                <pre class="prettyprint linenums lang-html">{{html}}</pre>
              </tab>
              <tab heading="TypeScript" *ngIf="ts">
                <pre class="prettyprint linenums lang-js">{{ts}}</pre>
              </tab>
            </tabset>
          </div>
        </div>

        <!-- remove this -->
        <div id="api" class="section" *ngIf="doc">
          <h3>Api</h3>
          <div class="item list-container" [innerHTML]="doc" ngNonBindable></div>
        </div>
      </div>
    </div>
    <app-footer></app-footer>
  </section>

  <add-nav class="add-nav"></add-nav>

</main>
