// demo/src/app/api-docs/sample-box/sample-box.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'ng-sample-box',
  templateUrl: './sample-box.component.html'
})
export class SampleBoxComponent {
  @Input() public ts: string;
  @Input() public html: string;
  @Input() public spec: string;
  @Input() public style: string;
}

<div class="section bd-example"><ng-content></ng-content></div>
<div id="markup" class="section">
  <div class="item">
    <tabset>
      <tab heading="template" *ngIf="html">
        <pre class="prettyprint linenums lang-html">{{html}}</pre>
      </tab>
      <tab heading="component" *ngIf="ts">
        <pre class="prettyprint linenums lang-js">{{ts}}</pre>
      </tab>
      <tab heading="tests" *ngIf="spec">
        <pre class="prettyprint linenums lang-js">{{spec}}</pre>
      </tab>
    </tabset>
  </div>
</div>

// packages/ngx-bootstrap-docs/src/components/sample-box/sample-box.tsx
import { component$, Slot } from '@builder.io/qwik';
import {Tab, Tabset} from "ngx-bootstrap";

export default component$((props:{html?: string, ts?: string, style?: string, spec?: string}) => {
    return (
        <>
            <div class="section bd-example">
                <Slot/>
            </div>
            <div class="section">
                <div class="item">
                {!!(props.html || props.ts || props.spec || props.style) && (
                    <Tabset>
                        {!!props.html && (
                            <Tab heading="template" id={'tab-template'} active={true}
                            customClass={'code-tab cursor-pointer'}>
                                <pre className="prettyprint linenums lang-html">{props.html}</pre>
                            </Tab>
                        )}

                        {!!props.ts && (
                            <Tab heading="component" id={'tab-component'}
                            customClass={'code-tab cursor-pointer'}>
                                <pre className="prettyprint linenums lang-js">{props.ts}</pre>
                            </Tab>
                        )}

                        {!!props.spec && (
                            <Tab heading="tests" id={'tab-tests'}
                            customClass={'code-tab cursor-pointer'}>
                                <pre className="prettyprint linenums lang-js">{props.spec}</pre>
                            </Tab>
                        )}

                        {!!props.style && (
                            <Tab heading="tests" id={'tab-style'}
                            customClass={'code-tab cursor-pointer'}>
                                <pre className="prettyprint linenums lang-css">{props.style}</pre>
                            </Tab>
                        )}
                    </Tabset>
                )}
            </div>
            </div>
        </>
    );
});
