// demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ContentSection } from '../../models/content-section.model';
import { ComponentExample } from '../../models/components-examples.model';

@Component({
  selector: 'examples',
  templateUrl: './examples.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class ExamplesComponent {
  examples: ComponentExample[];

  constructor(public section: ContentSection) {
    this.examples = section.content  as ComponentExample[];
  }
}

<ng-container *ngIf="section">
  <h2 [attr.id]="section.anchor">
    {{ section.name }}
    <a class="anchor-link" routerLink="." [fragment]="section.anchor">#</a>
  </h2>
  <p *ngIf="section.description" [innerHTML]="section.description"></p>

  <div *ngFor="let item of examples">
    <h3 *ngIf="item.title" [attr.id]="item.anchor">
      {{ item.title }}
      <a *ngIf="section.componentName && item.demoName"
         href="assets/stackblitz/{{section?.componentName}}-{{item?.demoName}}-bs{{isBs3 ? '3' : '4'}}.html"
         target="_blank"
         title="Open this demo in StackBlitz"
         class="stackblitz-link" >
        <img src="assets/images/stackblitz.png" alt="" width="20">
      </a>
      <a class="anchor-link" routerLink="." [fragment]="item.anchor">#</a>
    </h3>
    <p *ngIf="item.description" [innerHTML]="item.description"></p>
    <ng-sample-box [ts]="item.component" [html]="item.html">
      <ng-container *ngComponentOutlet="item.outlet"></ng-container>
    </ng-sample-box>
  </div>
</ng-container>

// packages/ngx-bootstrap-docs/src/components/examples-component/examples-component.tsx
import {component$, useClientEffect$, $, Slot, useStore} from '@builder.io/qwik';
import {getQueryParams} from "~/routing/routing";
import {tabsNames} from "~/components/docs-section/docs-section";
import SampleBox from '~/components/sample-box/sample-box';
import { ContentSection } from '~/models/content-section.model';


export default component$((props: {section:ContentSection}) => {
    const state = useStore({
        tabName: tabsNames.overview
    })

    useClientEffect$(() => {
        const key = tabsNames[getQueryParams('tab') as keyof typeof tabsNames]
        state.tabName = key || tabsNames.overview;
        console.log(props.section)
    });

    // const openStackBlitzDemo = $((comp, html) => {
    //     console.log(comp, html);
    // })

    return (

        <div class='examples'>
        {!!props.section?.description && (<p dangerouslySetInnerHTML={props.section?.description}></p>)}

        {props.section?.content?.map((item) => (
            <div class="example-section">
                {!!item.title &&
                    (<h3 id={item.anchor} class="d-flex justify-content-between">
                        { item.title }

                        {// @ts-ignore
                            !!(item?.component || state.tabName === 'examples') && (
                            <p class="m-0">
                                {!!(item.title !== 'Accessibility' && state.tabName !== 'examples') &&
                                    (<a
                                    title="Open this demo in StackBlitz"
                                    href="#"
                                    class="stackblitz-link"
                                    // onclick$={() => {
                                    //     // @ts-ignore
                                    //     openStackBlitzDemo(item?.component?.default, item?.html?.default)
                                    // }}
                                    >
                                    <img src="/images/stackblitz.png" alt="" width="20"/>
                                    </a>
                                    )
                                }

                                {/*<a *ngIf="tabName !== 'examples'" class="anchor-link d-inline-block" routerLink="." [fragment]="item.anchor">#</a>*/}
                                {/*<a *ngIf="item.title !== 'Accessibility' && tabName === 'examples'" [queryParams]="{tab: 'overview'}" routerLink="." [fragment]="initFragment(item.anchor)">*/}
                                {/*<img src="assets/images/icons/icon-code.svg" alt="" width="20">*/}
                                {/*</a>*/}
                            </p>
                        )}

                    </h3>)
                }

                {    // @ts-ignore
                    !!item.description && (
                    <p
                        // @ts-ignore
                        dangerouslySetInnerHTML={item.description}></p>
                )}

            <SampleBox
                // @ts-ignore
                html={item.html?.default} ts={item.component?.default} style={item.style}>
                <Slot></Slot>
            {/*<ng-container *ngComponentOutlet="item.outlet"></ng-container>*/}
            </SampleBox>
            </div>


        ))}


        </div>

    );
});
